version: '3.8'

services:
  php:
    container_name: hertz_backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MAILER_DSN: smtp://mailer:1025
      MAILER_TRANSPORT: smtp
      MAILER_HOST: mailer
      MAILER_PORT: 1025
    volumes:
      - .:/var/www/html
    depends_on:
      - database

  nginx:
    container_name: hertz_nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    container_name: hertz_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hertz_database
      MYSQL_USER: hertz_admin
      MYSQL_PASSWORD: hertz
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data:
